### ISSUE TITLE
Ability to use more than two different queries per layer

### ISSUE THREAD

**Issue by thomersch** [pka/t-rex#10]
I would like to be able to use multiple queries (in this case three), depending on the zoom level, because I use different generalised tables depending on zoom level.

Example:

    [[tileset.layer]]
    name = "waterareas"
    srid = 3857
    geometry_field = "geom"
    geometry_type = "MULTIPOLYGON"
    fid_field = "osm_id"

      [[tileset.layer.query]]
      sql = """
      SELECT osm_id, ST_Multi(geometry) AS geom
      FROM osm_waterareas
      WHERE geometry && !bbox!"""

      [[tileset.layer.query]]
      minzoom = 7
      maxzoom = 10
      sql = """
      SELECT osm_id, ST_Multi(geometry) AS geom
      FROM osm_waterareas_gen1
      WHERE geometry && !bbox!"""

      [[tileset.layer.query]]
      maxzoom = 6
      sql = """
      SELECT osm_id, ST_Multi(geometry) AS geom
      FROM osm_waterareas_gen0
      WHERE geometry && !bbox!"""

I tried this and that, but I could not achieve a consistent behaviour, I guess it isn't thought that way, right? Or is there a specific definition order I haven't understood yet?

**Comment by pka** [comment]
Your example looks right to me, but probably the algorithm is too simplistic.
When choosing the query for a given zoom level, it selects the first query entry with the requested zoom level within minzoom and maxzoom (https://github.com/pka/t-rex/blob/master/src/core/layer.rs#L68).
So if you place the default query at the end, it should work for now.

**Comment by pka** [comment]
After improving the algorithm to select a zoom dependent query, the behaviour for your example is still not clear between zoom levels 0 to 6. Shouldn't it be:

    [[tileset.layer]]
    name = "waterareas"
    srid = 3857
    geometry_field = "geom"
    geometry_type = "MULTIPOLYGON"
    fid_field = "osm_id"

      [[tileset.layer.query]]
      maxzoom = 6
      sql = """
      SELECT osm_id, ST_Multi(geometry) AS geom
      FROM osm_waterareas_gen0
      WHERE geometry && !bbox!"""

      [[tileset.layer.query]]
      minzoom = 7
      maxzoom = 10
      sql = """
      SELECT osm_id, ST_Multi(geometry) AS geom
      FROM osm_waterareas_gen1
      WHERE geometry && !bbox!"""

      [[tileset.layer.query]]
      minzoom = 11
      sql = """
      SELECT osm_id, ST_Multi(geometry) AS geom
      FROM osm_waterareas
      WHERE geometry && !bbox!"""
