### ISSUE TITLE
Empty tiles at zoomlevel 16 or greater

### ISSUE THREAD

**Issue by joostvenema** [pka/t-rex#16]
When I request tiles at zoomlevel 16, the coordinates of the Y-ax are way off. Below are 2 examples at level 15 and 16:

Zoomlevel 15: /15/16973/10716.pbf

```
DEBUG executing statement s5 with parameters: [720342.554559499, 6930698.228673499, 721565.5470120609, 6931921.221126061, 4.777314267823516, 18055.990933506204]
```

Zoomlevel 16: 16/33948/21433.pbf

```
DEBUG executing statement s4 with parameters: [721565.5470120609, -20037508.342789248, 722177.0432383418, -20036896.846562967, 2.388657133911758, 9027.995466753102]
```

**Comment by pka** [comment]
Your'e working with v0.6.1? Maybe this is fixed in the current master branch.
Will check that anyway, thanks for the feedback!

**Comment by joostvenema** [comment]
Hi,

I'm using the master branch. Also checked with 0.6.1, and is giving the same results.

Thanks for looking into it!

**Comment by pka** [comment]
Thanks a lot for fixing it!

**Comment by joostvenema** [comment]
My first lines in Rust ;-)

Happy to contribute, I think it's a great tool!
