### ISSUE TITLE
drawing issues on Mapbox

### ISSUE THREAD

**Issue by andreschardonguwo** [pka/t-rex#18]
T-rex is awesome. Everything seems to be working very well. However i'm having some issues with high-level zoom (above 12).  I'm attaching a few screenshots. Was wondering if it was an issue with zoom level. But not sure

![t-rex-pol-lines-more-erros](https://cloud.githubusercontent.com/assets/23097245/23836637/cc45af8e-0751-11e7-87c1-c30cafd6ab59.PNG)
![t-rex-pol-lines](https://cloud.githubusercontent.com/assets/23097245/23836638/cc462734-0751-11e7-8037-e342bcf3c19d.PNG)
![t-rex-pol-ok](https://cloud.githubusercontent.com/assets/23097245/23836639/cc466f0a-0751-11e7-8254-140d979b83b3.PNG)

**Comment by pka** [comment]
Looks strange indeed! Are these maps rendered with a built-in viewer? Which version?

**Comment by andreschardonguwo** [comment]
I'm trying with the latest version 0.33.1. However, happens on the built in as well. Also noticed that no issues with built in OpenLayers and XRay

**Comment by pka** [comment]
Then I'm supecting degerated geometries caused by clipping or simplification (see #5). Can you turn off simplification and play with the clipping parameters? I'm very interested in a dataset working with OL, but not with MB GL js. Is your datasource public or can you make it available for testing?

**Comment by andreschardonguwo** [comment]
Thank's for the reply. I will test without simplification later today. I also can share this dataset. It's a query on our postgis server. However, I can export as shape file or geojson.

**Comment by andreschardonguwo** [comment]
Tried to remove clipping and simplification = false, and the result is the same. Some polygons have holes. Maybe that's the issue. However, on OL they are correctly drawn. I can send you the dataset. What's the best format?

**Comment by pka** [comment]
Best option would be a PG dump (`pg_dump --file=out.dump --format=c --table=...`). A file export would maybe do it as well.

**Comment by andreschardonguwo** [comment]
Find attached the dump file. Let me know if you able to test it. Thank you very much!. 

[out.zip](https://github.com/pka/t-rex/files/844882/out.zip)

**Comment by pka** [comment]
Thanks for the data. I couldn't reproduce your output, but also saw some glitches when displaying it with Maputnik. A first look at the data shows some invalid geometries:

gid|st_npoints|st_nrings|st_isvaliddetail
---|----------|---------|----------------
162620|16348|11|(t,,)
162621|17451|9|(t,,)
162622|16006|6|(t,,)
162623|11674|8|(t,,)
162624|809|1|(t,,)
162625|12193|1|(t,,)
162626|22191|14|(f,"Too few points in geometry component",0101000000FBA45F828DCA53C1BED636691E7644C1)
162627|14718|2|(t,,)
162628|8661|2|(t,,)
162629|11419|9|(f,"Too few points in geometry component",01010000002E4D0730DEDB53C10198F0D8160045C1)
162630|8195|5|(f,"Too few points in geometry component",0101000000417405DD7AE553C132B7F7E9B3DC44C1)
162631|8441|9|(t,,)
162632|12311|4|(t,,)
162633|5055|1|(t,,)
162634|27981|10|(t,,)
162635|10026|2|(t,,)
162636|6761|2|(t,,)
162637|5083|1|(t,,)
162638|2663|1|(t,,)
162639|3961|1|(t,,)
162640|2929|1|(t,,)
162641|5122|1|(t,,)
162642|2513|1|(t,,)
162643|20223|10|(f,"Too few points in geometry component",010100000046B04456ECE453C1926402CE9EA644C1)
162644|6420|3|(t,,)
162645|3559|1|(t,,)
162646|2835|1|(t,,)

**Comment by andreschardonguwo** [comment]
Thank you @pka. I've published the layer and removed the invalid geometries, however, mabox still is drawing the lines.  OpenLayers still fine. 

![img2](https://cloud.githubusercontent.com/assets/23097245/24101964/a3bb78b4-0d50-11e7-8f10-fafd13f32017.png)
![img1](https://cloud.githubusercontent.com/assets/23097245/24101965/a3bbd886-0d50-11e7-832e-d6f46c1310b2.png)

**Comment by pka** [comment]
These artifacts are caused by unclipped polygons or lines. Clipping has been fixed for reprojected layers in 7801bb8 and in a6889b7 for config files written with versions 0.7.0-0.7.2.
Always use `buffer_size` in your configuration!
