### ISSUE TITLE
Error with loading template

### ISSUE THREAD

**Issue by spatialhast** [pka/t-rex#2]
I have problems with the launch of  t-rex server on Ubuntu 14.04 and Windows 7.
I import one polygonal layer in PostGIS database (EPSG:3857, singlepart features). 
When I run command 
```
~/t_rex serve --dbconn postgresql://postgres:postgres@localhost:5432/test (on Ubuntu)
t_rex.exe serve --dbconn postgresql://postgres:postgres@localhost:5432/test (on Windows)
```
and open URL http://127.0.0.1:6767/ in browser (or using command curl http://127.0.0.1:6767/) I receive error: 

> 2016-06-22 12:37:03.337 INFO GET /
> 2016-06-22 12:37:03.337 WARN Get V4(127.0.0.1:50338) AbsolutePath("/") "Failed to compile template \'src/webserver/templates/index.tpl\': Error { repr: Os { code: 2, message: \"No such file or directory\" } }" Some(InternalServerError)

Also I try run t-rex server with configuration file and get some error - I try change 'bind' and 'port' options in configuration file (When I  change 'bind' and 'port' options in configuration file and I run  t-rex server in console listening server remains unchanged 'Listening on http://127.0.0.1:6767'). 
What could be the problem?

**Comment by pka** [comment]
Templates are obviously not included in the exe file, contrary to my assumption. I'll try to include them or create a package with needed files, when necessary.
Thanks a lot for testing and reporting!

**Comment by pka** [comment]
Templates and static files are now included in the binaries.
