### ISSUE TITLE
Extend Web mercator grid definition to zoom level 22

### ISSUE THREAD

**Issue by Tom-Cuthill** [pka/t-rex#21]
Hi pka,

 I was wondering if it is possible to create group layers, ie. where the data in a layer comes from more than one table in PostGIS.  We love your work and were hoping to use it in a project that requires nearly two dozen tables to be grouped into 4 displayable layers.

Is this possible?  Any insights would be greatly appreciated.

Cheers,
Tom Cuthill

**Comment by pka** [comment]
A `tileset` is a collection of `tileset.layer`'s which groups layers using different tables. They are delivered within the same mvt file, but layers can still be displayed separately.
Do you want to deliver the ~20 tables within one mvt file, needing a mechanism to display them combined in 4 groups? If geometry types and attributes within these groups are the same, an SQL Union might already fullfill your need. If they are different, why not just turn the visibility of all layers within a group on/off together programatically?

**Comment by Tom-Cuthill** [comment]
Hi Permin,

Thanks, that is exactly what we are after!  I see that using the tileset name in the requesting URL instead of the layer name brings down all the tileset layers associated with the tileset itself.  So we'll have 4 tilesets with up to 6 layers in each.

I notice that in the grid definition for web mercator you go down to zoom level 18.  Some of our layers are very fine grain, best viewed at zoom levels 19 - 20.  From what I've read the Google TMS usually go down to zoom level 22.  Did you decide to stop at level 18, because your tile extent is 4096, which kind of takes you 4 levels deeper?  If we do create a custom grid, which is the same as web mercator (EPSG:3857) but going down to a greater zoom level, will that cause any problems?

Thanks again for your help,
Tom

**Comment by pka** [comment]
Hi Tom,

Good to hear that tilesets cover you needs.
The Webmercator grid definition is taken from MapCache. Makes sense to extend it to zoom level 22.

Cheers
Pirmin

**Comment by pka** [comment]
Done in v0.7.2
