### ISSUE TITLE
Add a basemap

### ISSUE THREAD

**Issue by diskmanti** [pka/t-rex#28]
Hello and first of all congrats for working on this project. It is on the of the best and easiest vector server to use. :+1: 

Since I use data for Albania, which is a very small country, sometimes is difficult to see the rendered data in the browser. Would it be possible to have a basemap  for quick reference.

Cheers.

**Comment by pka** [comment]
I'm having the same problem testing with Switzerland or even Lichtenstein...
Do you expect a background map in all viewers, or just in one (e.g. MB GL)?
Before adding a basemap, the BBOX should be detected and returned in the TileJson metadata, so viewers can automatically zoom the available data.

**Comment by diskmanti** [comment]
The ideal would be to have a basemap for all the viewers, but if it is too much work I think to have it in one viewer would also be ok.

**Comment by pka** [comment]
0.7.4 includes an automatic layer extent detection and the viewer zooms to this extent. So you should find your data now.

**Comment by diskmanti** [comment]
I am running some test with the new version of t_rex, but it seems something breaks. I am running the genconfig command to create a new config file, but some error popups. If I use an old config tile the server starts but it does not zoom to the data extent.
---

This is the messages it shows 

```bash
2017-06-26 16:17:25.159 INFO Detecting layers from geometry_columns
2017-06-26 16:17:25.341 WARN Multiple geometry types in 'road_areas.way': LINESTRING, POLYGON
2017-06-26 16:17:25.368 WARN Multiple geometry types in 'recreation_polygon.way': MULTIPOLYGON, POLYGON
2017-06-26 16:17:25.440 WARN Multiple geometry types in 'pier_area.way': LINESTRING, POLYGON
2017-06-26 16:17:25.520 WARN Multiple geometry types in 'buildings.way': LINESTRING, POLYGON
2017-06-26 16:17:25.538 WARN Multiple geometry types in 'addresses_polygon.way': LINESTRING, POLYGON
thread 'main' panicked at 'error retrieving column "extent": Conversion(WasNull)', /cargo/registry/src/github.com-1ecc6299db9ec823/postgres-0.14.1/src/rows.rs:206
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

**Comment by pka** [comment]
You've hit a bug when detecting the extent of empty tables. I've fixed this case and made a new release. Thanks for reporting.

**Comment by diskmanti** [comment]
I believe that this issue should be closed now.
