### ISSUE TITLE
pbf vs mvt

### ISSUE THREAD

**Issue by musicformellons** [pka/t-rex#33]
I used to have mvt tiles but now see pbf is returned. I think they are pretty similar?! Could you maybe comment why pbf is supported and mvt not?

**Comment by pka** [comment]
MVT means "Mapbox Vector Tiles". According to the [spec](https://github.com/mapbox/vector-tile-spec/tree/master/2.1) Mapbox Vector Tiles are stored in Protobuf (pbf) format . So for me, mvt and pbf is the same. Does a certain software expect an "mvt" file suffix?

**Comment by musicformellons** [comment]
It looks like mapbox-gl-js can handle both. 

Mapzen tileserver exports the .mvt suffix for its vector tiles. Here it is used by mapbox e.g.:
https://www.mapbox.com/mapbox-gl-js/example/third-party/

**Comment by Nachtmeer** [comment]
I try to use t-rex for serving tiles for a harp.gl application and there only mvt is supported for the Mapbox API format.
Wouldn't it be nice to have an option in the config file for choosing the suffix of the output files? For now i will just automatically rename all files t-rex has created.
