### ISSUE TITLE
how to visually check pbf response?

### ISSUE THREAD

**Issue by musicformellons** [pka/t-rex#34]
I have a customlayer in postgres with 50000 points. I used to work with a server that could return mvt and json. When I visually wanted to check the response I simply used json and could see the curl result in the terminal. I now have migrated to t-rex and everything looks fine and dandy except that my points are not shown on the map... I am running t-rex on a remote server and trying to browse my customlayer with mapbox-gl-js on my local pc:
- when I drag the map I can see t-rex giving responses for tiles that have not been queried before etc.
- when on my local pc I do:
`curl -s http://<remoteIPaddress>:8080/customlayer/4/2/6.pbf`
It returns
![screenshot from 2017-06-22 15-15-25](https://user-images.githubusercontent.com/10334123/27435945-f1d38e04-575d-11e7-9ab6-09403442893e.png)
 So garbled output, but could be correct output.
- There are no errormesages in the browser console, except when I zoom >22, which makes sense.

So how to proceed? How can I (visually) verify whether my points are actually in the pbf tiles, so I can check what is wrong? 

My config.toml:

```
# t-rex configuration

[service.mvt]
viewer = true

[datasource]
type = "postgis"
url = "postgresql://usr:pw@localhost/dbname"

[grid]
# Predefined grids: web_mercator, wgs84
predefined = "web_mercator"

[[tileset]]
name = "customlayer"

[[tileset.layer]]
name = "customlayer"
table_name = "customlayer"
geometry_field = "wkb_geometry"
geometry_type = "POINT"
srid = 4326
#fid_field = "id"
#buffer_size = 10
query_limit = 100000
#[[tileset.layer.query]]
#sql = """SELECT ST_Transform(wkb_geometry,3857) AS wkb_geometry,"ogc_fid","image","city","url" FROM customlayer WHERE wkb_geometry && !bbox!"""

[cache.file]
base = "/tmp/mvtcache"

[webserver]
# Bind address. Use 0.0.0.0 to listen on all adresses.
bind = "<remoteIPaddress>"
port = 8080
threads = 4


```

**Comment by kiambogo** [comment]
Did you try viewing the map through the built-in viewer? It provides out-of-the-box viewers for Mapbox GL JS, Openlayers, and other debug tools. I would first test here, as it could be an issue with your Mapbox GL JS implementation locally (layers/styling not configured properly). The viewer can be accessed by pointing your browser to the instance running t-rex (i.e. http://<remoteIPaddress>:8080). You may need to zoom/pan around to find your points. Using Inspector, you can also click on the different tiles to get more info (like # of features). 

Finally, @pka also included instructions in the README for decoding vector tiles so you can view the payload in each tile:

    curl --silent http://127.0.0.1:6767/ne_10m_populated_places/5/31/17.pbf | gunzip -d | protoc --decode=vector_tile.Tile src/mvt/vector_tile.proto

**Comment by musicformellons** [comment]
I tried the the viewer. It looks nice, but does not return my points when I look under the mapbox tab. I actually would expect to -at least- have a zoomin&out widget (as it is included under the OpenLayers tab...), but I have just white, nothing else. 

Part of my confusion is that it seems I need to add some styling as the viewer mentions:
Style JSON: http://151.80.145.127:8080/customlayer.style.json
Or is this autogenerated and thus not really necessary to add?)

The confusion comes from the fact that my styling -thus far- has been part of my mapbox-gl-js setup (so separate from the vector tiles... I am just looking for serving 'unstyled' tiles, but without styling my points might not show in the viewer?

I also tried decoding vector tiles. As I seemed to need one I supplied a proto file from here:
https://raw.githubusercontent.com/mapbox/vector-tile-spec/master/2.1/vector_tile.proto

And then did:
`$ curl --silent http://<remoteIPaddress>:8080/markers/1/2/6.pbf | gunzip -d | protoc --decode=vector_tile.Tile vector_tile.proto`
I get:
```
layers {
  name: "customlayer"
  extent: 4096
  version: 2
}
```
and that's it. Does this mean there are no points in that tile? As I am sure it should contain many of my points, this would be good to know. 

BTW: the coords of the points I uploaded were in mercator (so not wgs84) format. This worked for the tileserver I had before, but am wondering if this could be a culprit of my troubles maybe?

**Comment by pka** [comment]
This tile looks empty indeed. You write that your data was in mercator projection, but your config says that the layer data is in SRID 4326, which is WGS84. So t-rex transforms from 4326 to 3857 (Web Mercator). This could be the reason for missing data. Maybe you had wrong paraemeters in DB loading process?

When you set `RUST_LOG=debug` (e.g. `RUST_LOG=debug t_rex serve` ...) you get additional log output including the SQL queries. So you can check manually why no data is found.

**Comment by musicformellons** [comment]
Ha! After changing srid = 4326 into srid = 3857 in the config.toml it works within my mapbox-gl-js app! Looks really good and fast!

However, my points still do not show within the viewer (both not mapbox-gl and openlayers). Why is that? Styling?

**Comment by pka** [comment]
I guess because of cached tiles. Empty the browser cache and try again.

**Comment by musicformellons** [comment]
Yep, that did the trick. As there is no basemap it is hard to see whether my points are 'correct'. They seem on different places (maybe to do with the 'srid trick' I did). In my app everything is working brilliantly. Very happy!
