### ISSUE TITLE
points do not show (due to tileborder?!)

### ISSUE THREAD

**Issue by musicformellons** [pka/t-rex#35]
When I zooming in at a certain map area the points disappear and then reappear at a slightly higher zoom again. See pictures for example. Second picture is at higher zoom. I could add a lower zoom in which the points are shown before they disappear, but I forgot to do so. Hope it is clear enough.
![screenshot from 2017-06-22 22-19-56](https://user-images.githubusercontent.com/10334123/27454976-164c0d04-579c-11e7-8d36-ddbd8df28ff8.png)
![screenshot from 2017-06-22 22-20-24](https://user-images.githubusercontent.com/10334123/27454978-19735a8c-579c-11e7-8dc3-5d46248d8157.png)

**Comment by kiambogo** [comment]
See https://github.com/pka/t-rex/issues/24

TL;DR - increase your query limits, or don't set a query limit.

**Comment by musicformellons** [comment]
Thx. It's gone before I changed my query limit (which was set at 100000): I generated cache files and cleared the browser cache.
