### ISSUE TITLE
what nodeno and nodes options do exactly?

### ISSUE THREAD

**Issue by musicformellons** [pka/t-rex#36]
After generating lots of cache tiles I get 'No space left on device' for basically every interaction with my machine. This seemed strange at first as my disk space was at 50% or so. After some digging it appears to be that I ran out of inodes on the /dev/vda1 partition:

```
root@vps412437:/home/usr# df -i
Filesystem      Inodes   IUsed  IFree IUse% Mounted on
udev            247614     403 247211    1% /dev
tmpfs           249890     520 249370    1% /run
/dev/vda1      1280000 1280000      0  100% /
tmpfs           249890       3 249887    1% /dev/shm
tmpfs           249890       3 249887    1% /run/lock
tmpfs           249890      16 249874    1% /sys/fs/cgroup
tmpfs           249890       4 249886    1% /run/user/0
```

It seems you need to create more inodes at system install to solve this (or of course have a bigger machine from the start... 

From this background I was wondering what the cache generation options:
        --nodeno <NUM>                    Number of this nodes (0 <= n < nodes)
        --nodes <NUM>                     Number of generator nodes

do?

**Comment by pka** [comment]
You are hit by one of the major problems with tiles - a huge number of files. You have to tune or switch your FS or store your tiles somewhere else (e.g. S3).
The nodes/nodeno parameters are made for parallel cache generation. You generete tiles on x machines, aka nodes (parameter --nodes=x) and tell each process on which computer it's running (--nodeno=0..x-1). This allows t-rex to generate parts of the cache on each computer in parallel.
