### ISSUE TITLE
Proper config for # of threads

### ISSUE THREAD

**Issue by musicformellons** [pka/t-rex#40]
What is the 'rule of thumb' here? Does this have to be similar to your # of cores?

**Comment by pka** [comment]
Currently the # of threads is limiting the # of parallel connections. So it has to be increased when there are more clients and/or more connections per client.

**Comment by musicformellons** [comment]
Ok, so it is not really limited by your server's processor/cores then, I suppose. I just read somewhere that modern browsers use 2-6 parallel connections per domain. Thanks.
