### ISSUE TITLE
insert records

### ISSUE THREAD

**Issue by musicformellons** [pka/t-rex#42]
I would like to insert records (points) from the client browser into the postgis database. This is not included in t-rex. Is this something that could be added in the future? Could I just run another server (e.g. express.js) next to t-rex to provide me with this user data feature? I am on unknown territory...

**Comment by musicformellons** [comment]
Mmmh, as t-rex uses nickel it might be more sense to use nickel for this? 

BTW, did you consider using rocket?: 
https://rocket.rs/

**Comment by pka** [comment]
Collecting data is not in the scope of t-rex. Tools for this are e.g. [GDAL](http://www.gdal.org/ogr2ogr.html) or [QGIS](http://qgis.org). You can also write data from a web application (say Rocket with Rust nightly), but in the end you will need [rust-postgis](https://github.com/andelf/rust-postgis) or [rust-gdal](https://github.com/georust/rust-gdal).
