### ISSUE TITLE
v0.8.0-pre1 - OpenSSL version issues

### ISSUE THREAD

**Issue by snadon** [pka/t-rex#53]
On a fresh debian 9.1 install, I cannot run any t_rex command because of the ssl version installed.

`t_rex: error while loading shared libraries: libssl.so.1.0.0: cannot open shared object file: No such file or directory`

Here's what's installed by default:
```
/usr/lib/x86_64-linux-gnu/libssl3.so
/usr/lib/x86_64-linux-gnu/libssl.so.1.0.2
/usr/lib/x86_64-linux-gnu/libssl.so.1.1
OpenSSL 1.1.0f # openssl version
```

When trying to symlink 1.1 to 1.0.0 (just curious) it's telling me OpenSSL 1.0.0 is not installed.

What should I do?

Also, at this moment I don't need to use ssl. Is there a flag to skip it?

Thank you!

**Comment by pka** [comment]
The binary is built on the Travis Ubuntu image. SSL support is activated [here](https://github.com/pka/t-rex/blob/master/t-rex-core/Cargo.toml#L29). It should use the correct library version when built locally with `cargo build`.

**Comment by snadon** [comment]
Thank you for your response.

The website says Debian/Ubuntu (see http://t-rex.tileserver.ch/doc/setup/#installation) so it got me confused.

Following your answer, I tried to `cargo build` after git cloning t-rex (branch v0.8.0-pre1) and when building I get this error:

```
root@test:/home/debian/t-rex# cargo build --verbose
    Updating git repository `https://github.com/pka/rust-gdal`
error: failed to load source for a dependency on `gdal`

Caused by:
  Unable to update https://github.com/pka/rust-gdal?branch=t-rex#3c181711

Caused by:
  [4/-3] revspec '3c18171167bc59f7803c7fe8c9406b4c4fd059ec' not found

root@test:/home/debian/t-rex# rustup show
Default host: x86_64-unknown-linux-gnu

stable-x86_64-unknown-linux-gnu (default)
rustc 1.19.0 (0ade33941 2017-07-17)
```

**Comment by snadon** [comment]
To fix the issue below, I had to run `cargo update`. However, after `cargo build --release` I got an OPENSSL_DIR error and after a couple fixes it still wasn't working for Debian. After reading more issues on rust-openssl, I decided to restart my installation with Ubuntu instead.

This issue can be closed.
