### ISSUE TITLE
Error converting between Postgres and Rust types

### ISSUE THREAD

**Issue by clouddie** [pka/t-rex#6]
Hi, this looks like a promising project. I am having nightmares trying to get node-mapnik output vector tiles properly, so when I saw your project I saw a glimpse of hope...

I have not managed to make it work, though (I am a complete amateur by the way), version pre7 fails with hundreds of lines of :

```
2016-08-15 00:03:44.847 ERROR Layer 'city_object': Error converting between Postgres and Rust types: cannot convert geometry to Geometry
2016-08-15 00:03:44.850 ERROR Row { statement: Statement { name: "s0", parameter_types: [Float8, Float8, Float8, Float8], columns: [Column { name: "geometry", type_: Other(Other { name: "geometry", oid: 116463, kind: Simple, schema: "public" }) }] } }
```

I tried to limit shapes to POLYGON, as referenced in #3, but it did not work.

I am intringued by the way as to why resort to rust to output vector tiles, where there are already existing tools (native mapnik C++, node bindings for mapnik, and python bindings at Mapzen) ? What are the benefits of going with rust (including serving tiles, seems far-fetched).

**Comment by pka** [comment]
Rust is a modern programming language with compelling features. It has a strict type system which makes handling generic types like GEOMETRY or NUMERIC harder.
My plan is to convert generic types automatically (e..g NUMERIC into TEXT) to avoid these messages.
Thanks for your feedback!

**Comment by pka** [comment]
The recent version 0.2.0 introduces several automatic type conversions. You should also get fewer messages, because the queries are prepared at startup.

**Comment by clouddie** [comment]
Thanks, will give it a go !

Le 30 août 2016 00:56, "Pirmin Kalberer" <notifications@github.com> a
écrit :
